spring:
  thymeleaf:
    cache: false
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost/marusei?connectionCollation=utf8mb4_bin
      username: root
      password: '1234'
      maximum-pool-size: 1
logging:
  level:
    com.github.smdj.marusei: debug
    com.github.smdj.marusei.Launcher: trace
    com.github.smdj.marusei.controller: trace